name: Categories
form: $/sntools/assets/models/category/fields.yaml
modelClass: Sntools\Assets\Models\Category
defaultRedirect: sntools/assets/categories
create:
    redirect: 'sntools/assets/categories/update/:id'
    redirectClose: sntools/assets/categories
update:
    redirect: sntools/assets/categories
    redirectClose: sntools/assets/categories
