list: $/sntools/assets/models/category/columns.yaml
modelClass: Sntools\Assets\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sntools/assets/categories/update/:id'
