list: $/butils/assets/models/asset/columns.yaml
modelClass: Butils\Assets\Models\Asset
title: Assets
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'butils/assets/assets/update/:id'
defaultSort:
    column: 'name'
    direction: 'asc'
