name: Assets
form: $/sntools/assets/models/asset/fields.yaml
modelClass: Sntools\Assets\Models\Asset
defaultRedirect: sntools/assets/assets
create:
    redirect: 'sntools/assets/assets/update/:id'
    redirectClose: sntools/assets/assets
update:
    redirect: sntools/assets/assets
    redirectClose: sntools/assets/assets
